spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  profiles:
    active: dev


mybatis:
  type-aliases-package: com.yikolemon.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true